# Generated by Django 5.1.6 on 2026-05-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_add_report_model_post_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('message', 'Message de chat'), ('group_message', 'Message de groupe'), ('post', "Post L'Entracte"), ('comment', "Commentaire L'Entracte")], max_length=20),
        ),
    ]
