# Generated by Django 5.1.6 on 2026-03-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilefilmsignature',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='profilefilmsignature',
            name='rating',
        ),
        migrations.AddField(
            model_name='profilefilmsignature',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mood',
            field=models.CharField(blank=True, choices=[('rire', 'Envie de rire'), ('reflechir', 'Besoin de reflechir'), ('emu', "Envie d'etre emu"), ('adrenaline', "Besoin d'adrenaline")], max_length=20),
        ),
    ]
