# Generated by Django 5.1.6 on 2026-05-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_email_verification_lang_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cgu_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
