# Generated by Django 5.1.6 on 2026-03-26 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinepolis_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(default='BE', max_length=2)),
                ('language', models.CharField(default='FR', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'films_cinema',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'films_genre',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinepolis_id', models.CharField(max_length=50, unique=True)),
                ('corporate_id', models.IntegerField(blank=True, null=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('imdb_code', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('synopsis', models.TextField(blank=True)),
                ('short_synopsis', models.TextField(blank=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(default='FR', max_length=5)),
                ('audio_language', models.CharField(blank=True, max_length=5)),
                ('is_future', models.BooleanField(default=False)),
                ('poster_url', models.URLField(blank=True)),
                ('backdrop_url', models.URLField(blank=True)),
                ('trailer_youtube_key', models.CharField(blank=True, max_length=50)),
                ('tmdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, to='films.genre')),
            ],
            options={
                'db_table': 'films_film',
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinepolis_session_id', models.CharField(max_length=50, unique=True)),
                ('showtime', models.DateTimeField(db_index=True)),
                ('language', models.CharField(default='FR', max_length=5)),
                ('hall', models.IntegerField(blank=True, null=True)),
                ('vista_session_id', models.IntegerField(blank=True, null=True)),
                ('is_sold_out', models.BooleanField(default=False)),
                ('has_cosy_seating', models.BooleanField(default=False)),
                ('booking_url', models.URLField(blank=True)),
                ('raw_attributes', models.CharField(blank=True, max_length=100)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='films.cinema')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='films.film')),
            ],
            options={
                'db_table': 'films_seance',
                'ordering': ['showtime'],
            },
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['title'], name='films_film_title_72d7db_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['is_future', '-release_date'], name='films_film_is_futu_60aa4d_idx'),
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['film', 'cinema', 'showtime'], name='films_seanc_film_id_b64cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['showtime'], name='films_seanc_showtim_8bc725_idx'),
        ),
    ]
