# Generated by Django 5.1.6 on 2026-03-08 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocine_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'films_cinema_chain',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'films_genre',
            },
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocine_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(default='BE', max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='films.cinemachain')),
            ],
            options={
                'db_table': 'films_cinema',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('titre', models.CharField(db_index=True, max_length=255)),
                ('titre_original', models.CharField(max_length=255)),
                ('synopsis', models.TextField(blank=True)),
                ('poster', models.URLField(blank=True)),
                ('backdrop', models.URLField(blank=True)),
                ('trailer_youtube_key', models.CharField(blank=True, max_length=50)),
                ('duree', models.IntegerField(blank=True, null=True)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('note', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('vote_count', models.IntegerField(default=0)),
                ('is_now_playing', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, to='films.genre')),
            ],
            options={
                'db_table': 'films_film',
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(db_index=True)),
                ('version', models.CharField(choices=[('VF', 'VF'), ('VO', 'VO'), ('VOST', 'VOST')], default='VF', max_length=4)),
                ('format', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX'), ('4DX', '4DX')], default='2D', max_length=10)),
                ('places_restantes', models.IntegerField(blank=True, null=True)),
                ('booking_url', models.URLField(blank=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='films.cinema')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='films.film')),
            ],
            options={
                'db_table': 'films_seance',
            },
        ),
        migrations.AddIndex(
            model_name='cinema',
            index=models.Index(fields=['city'], name='films_cinem_city_3ee4d5_idx'),
        ),
        migrations.AddIndex(
            model_name='cinema',
            index=models.Index(fields=['is_active'], name='films_cinem_is_acti_27e26f_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['titre'], name='films_film_titre_e1c91b_idx'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['is_now_playing', '-date_sortie'], name='films_film_is_now__073c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['film', 'cinema', 'date_heure'], name='films_seanc_film_id_7197a8_idx'),
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['date_heure'], name='films_seanc_date_he_91180c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seance',
            unique_together={('film', 'cinema', 'date_heure', 'version', 'format')},
        ),
    ]
