# Generated by Django 5.1.6 on 2026-05-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_add_watched_film_special_event_min_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='cast',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='film',
            name='crew',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
