# Generated by Django 5.1.6 on 2026-03-08 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('films', '0001_initial'),
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plannedouting',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outings', to='matching.match'),
        ),
        migrations.AddField(
            model_name='plannedouting',
            name='proposer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outings_proposed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plannedouting',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.seance'),
        ),
        migrations.AddField(
            model_name='review',
            name='outing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='matching.plannedouting'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swipe',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swipe',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('user1', 'user2')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('outing', 'reviewer')},
        ),
        migrations.AddIndex(
            model_name='swipe',
            index=models.Index(fields=['from_user', 'to_user', 'action'], name='matching_sw_from_us_f43b2c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='swipe',
            unique_together={('from_user', 'to_user')},
        ),
    ]
