# Generated by Django 5.1.6 on 2026-03-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ai_generated_reasons',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='match',
            name='ai_match_message',
            field=models.TextField(blank=True),
        ),
    ]
