# Generated by Django 5.1.6 on 2026-04-13 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
        ('matching', '0003_match_ai_generated_reasons_match_ai_match_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plannedouting',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='plannedouting',
            name='proposal_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plannedouting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='plannedouting',
            name='seance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outings', to='films.seance'),
        ),
    ]
