# Generated by Django 5.1.6 on 2026-03-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='contenu',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='lu',
            new_name='is_read',
        ),
        migrations.AddField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
